# Generated by Django 4.1 on 2023-05-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidaddefomento',
            name='id',
        ),
        migrations.AlterField(
            model_name='unidaddefomento',
            name='fecha',
            field=models.DateField(primary_key=True, serialize=False, unique=True, verbose_name='Fecha'),
        ),
    ]
